### ISSUE TITLE
Could not load dynamic library 'libcudart.so.11.0'

### ISSUE THREAD

**Issue by navuitag** [VNOpenAI/vn-aidr#5]
Hi @vietanhdev ,

I am a newbie to AI&ML. I am very impressed with this project. I tried to run it on my iMac with docker. But I got this error. Can you help me to resolve it?

Many thanks.

[Error image here](https://imgur.com/a/FdvwwU9)

~~~ini
docker run -it -p 8080:8080 vnaidr
2022-09-29 09:11:50.024991: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-29 09:11:50.885497: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/appuser/.local/lib/python3.8/site-packages/cv2/../../lib64:
2022-09-29 09:11:50.885563: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-09-29 09:11:51.009429: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-09-29 09:11:52.213252: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/appuser/.local/lib/python3.8/site-packages/cv2/../../lib64:
2022-09-29 09:11:52.214585: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/appuser/.local/lib/python3.8/site-packages/cv2/../../lib64:
2022-09-29 09:11:52.216723: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/appuser/.local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/appuser/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/appuser/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/appuser/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/appuser/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/appuser/.local/lib/python3.8/site-packages/uvicorn/main.py", line 408, in main
    run(
  File "/home/appuser/.local/lib/python3.8/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/home/appuser/.local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/appuser/.local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/appuser/.local/lib/python3.8/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/appuser/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/appuser/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/appuser/app/./app.py", line 16, in <module>
    from runners.vn_accent import VNAccentRunner
  File "/home/appuser/app/./runners/vn_accent.py", line 7, in <module>
    from model_utils.vn_accent.accent_utils import extract_words, remove_tone_line
ModuleNotFoundError: No module named 'model_utils.vn_accent.accent_utils'
~~~

**Comment by navuitag** [comment]
I resolved this issue by myself.
Release this source code on AWS environment.
1. AMI name: Deep Learning AMI GPU TensorFlow 2.10.0 (Ubuntu 20.04) 20220927
2. Instance Type: g4dn.xlarge
3. Issues resolution: downgrade tesorflow ans torch

~~~bash
python -m pip install --upgrade tensorflow==2.9.2
python -m pip uninstall torch torchaudio torchvision
python -m pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
~~~
